stages:
    - deploy

deploy-release:
    stage: deploy
    script:
        - npm install --registry https://registry.npm.taobao.org
        - npm run build
    tags:
        - shell
    only:
        - /^release.*$/
